FROM node:25-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:25-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY .env .
RUN mkdir -p ./public

RUN npm run build
RUN npx tsc && npx tsc-alias --resolve-full-paths

FROM node:25-alpine AS app
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/dist/server ./server
COPY --from=builder /app/dist/shared ./shared
COPY --from=builder /app/package.json ./
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
EXPOSE 3016
ENTRYPOINT ["npm", "run"]
